package app.idl.domain.avatar

import app.idl.domain.Availability
import app.idl.domain.Mood
import app.idl.domain.PresenceVisual
import app.idl.domain.PresenceView
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Golden composition vectors: a filtered PresenceView plus the shipped pack resolve to a
 * deterministic layer id list. Kotlin-only (AP-7). Regenerate with
 * `-Pidl.updateGolden=true`.
 */
class CompositionVectorsTest {
    private val registry = coreRegistry()
    private val resolver = AvatarResolver(registry)
    private val json = Json(app.idl.domain.IdlJson) { prettyPrint = true }

    @Serializable
    data class Case(
        val name: String,
        val view: PresenceView,
        val target: RenderTarget = RenderTarget.STANDARD_WIDGET,
        val expectedLayerIds: List<String> = emptyList(),
    )

    @Serializable
    data class Vectors(val note: String, val cases: List<Case>)

    private fun layers(view: PresenceView, target: RenderTarget = RenderTarget.STANDARD_WIDGET): List<String> {
        val presence = LegacyAvatarMigration.presence(view)
        val resolved = resolver.resolve(
            AvatarRenderRequest(
                configuration = view.identity,
                presence = presence,
                target = target,
                sizePx = target.defaultSizePx,
            ),
        )
        return resolved.layers.map { it.assetId }
    }

    private fun identity(
        palette: String = "palette_sunny",
        face: String? = null,
        resting: String = "neutral",
    ) = AvatarConfiguration(
        baseAssetId = "base_teardrop",
        paletteAssetId = palette,
        signatureFaceAccessoryAssetId = face,
        restingExpressionId = resting,
        familyId = "teardrop_face",
    )

    private fun cases(): List<Case> {
        val resting = PresenceView(userId = "u", identity = identity(face = "face_glasses_round"))
        val friendHiddenMood = PresenceView(
            userId = "u",
            identity = identity(face = "face_glasses_round", resting = "happy"),
            availability = Availability.TEXT_ONLY,
            visual = PresenceVisual(propAssetId = "prop_tea", sceneAssetId = "scene_cozy_bedroom"),
        )
        val closeWithMood = PresenceView(
            userId = "u",
            identity = identity(face = "face_glasses_round", resting = "happy"),
            mood = Mood.SLEEPY,
            availability = Availability.TEXT_ONLY,
            visual = PresenceVisual(
                expressionId = "sleepy",
                propAssetId = "prop_tea",
                bodyAccessoryAssetId = "body_blanket",
                sceneAssetId = "scene_cozy_bedroom",
            ),
        )
        return listOf(
            Case("resting glasses", resting, expectedLayerIds = layers(resting)),
            Case("friend hides mood expression", friendHiddenMood, expectedLayerIds = layers(friendHiddenMood)),
            Case("close friend sleepy face", closeWithMood, expectedLayerIds = layers(closeWithMood)),
        )
    }

    @Test fun `golden composition vectors are up to date`() {
        val generated = json.encodeToString(
            Vectors.serializer(),
            Vectors(
                note = "Generated by CompositionVectorsTest. Do not edit by hand.",
                cases = cases(),
            ),
        ) + "\n"
        val file = goldenFile()
        if (System.getProperty("idl.updateGolden") == "true" || !file.exists()) {
            file.parentFile.mkdirs()
            file.writeText(generated)
        }
        assertEquals(
            "contract/composition_vectors.json is stale; rerun with -Pidl.updateGolden=true and review the diff",
            generated,
            file.readText().replace("\r\n", "\n"),
        )
    }

    @Test fun `hidden mood never resolves a mood expression layer`() {
        val view = PresenceView(
            userId = "u",
            identity = identity(resting = "happy"),
            availability = Availability.BUSY,
            visual = PresenceVisual(propAssetId = "prop_tea"),
        )
        val ids = layers(view)
        assertFalse(ids.any { it.startsWith("overlay_") })
        // Resting happy stays on identity; presence must not invent a mood face from availability.
        assertFalse("sleepy" in ids)
        assertFalse("anxious" in ids)
        assertFalse("dnd" in ids)
        assertTrue(ids.contains("prop_tea"))
    }

    @Test fun `mutation check - leaking expressionId without mood changes composition`() {
        val clean = PresenceView(
            userId = "u",
            identity = identity(),
            availability = Availability.TEXT_ONLY,
            visual = PresenceVisual(propAssetId = "prop_tea"),
        )
        val leaked = clean.copy(visual = clean.visual!!.copy(expressionId = "sleepy"))
        // LegacyAvatarMigration.presence strips expressionId when mood is null, so the leak must
        // be injected after that filter to prove the vector would catch a buggy client.
        val cleanIds = layers(clean)
        val leakedPresence = LegacyAvatarMigration.presence(leaked).copy(expressionId = "sleepy")
        val leakedIds = resolver.resolve(
            AvatarRenderRequest(
                configuration = leaked.identity,
                presence = leakedPresence,
                target = RenderTarget.STANDARD_WIDGET,
                sizePx = RenderTarget.STANDARD_WIDGET.defaultSizePx,
            ),
        ).layers.map { it.assetId }
        assertFalse(
            "deliberate mood-expression leak must change resolved layers",
            cleanIds == leakedIds,
        )
    }

    private fun goldenFile(): File {
        var dir: File? = File("").absoluteFile
        while (dir != null && !File(dir, "settings.gradle.kts").exists()) dir = dir.parentFile
        return File(requireNotNull(dir) { "repo root not found" }, "contract/composition_vectors.json")
    }
}
