"""Build the server asset catalog from the shipped pack manifests.

Stdlib only. Writes contract/asset_catalog.json and the SQL seed fragment
embedded by the AP-7 migration. `check` fails if either is stale.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKS = ROOT / "app" / "src" / "main" / "assets" / "packs"
SHIPPED = [
    ("core_proto", 1),
    ("emoji_core", 2),
]
OUT_JSON = ROOT / "contract" / "asset_catalog.json"
OUT_SQL = ROOT / "supabase" / "seed" / "asset_catalog_seed.sql"


def load_manifest(pack_id: str, version: int) -> dict:
    path = PACKS / pack_id / f"v{version}" / "manifest.json"
    return json.loads(path.read_text(encoding="utf-8"))


def build() -> dict:
    assets: list[dict] = []
    retired: dict[str, str] = {}
    seen: set[str] = set()
    for pack_id, version in SHIPPED:
        manifest = load_manifest(pack_id, version)
        for asset in manifest.get("assets", []):
            asset_id = asset["id"]
            if asset_id in seen:
                raise SystemExit(f"duplicate asset id {asset_id}")
            seen.add(asset_id)
            assets.append(
                {
                    "assetId": asset_id,
                    "packId": pack_id,
                    "packVersion": version,
                    "category": asset["category"],
                    "tier": asset.get("tier", "free"),
                    "widgetSafe": asset.get("widgetSafe", True),
                }
            )
        for old, new in manifest.get("retired", {}).items():
            if old in retired and retired[old] != new:
                raise SystemExit(f"conflicting retirement for {old}")
            retired[old] = new
    assets.sort(key=lambda a: a["assetId"])
    return {
        "note": "Generated by tools/gen_asset_catalog.py from shipped manifests. Do not edit by hand.",
        "assets": assets,
        "retired": dict(sorted(retired.items())),
    }


def sql_seed(catalog: dict) -> str:
    lines = [
        "-- Generated by tools/gen_asset_catalog.py. Do not edit by hand.",
        "truncate idl_private.asset_catalog;",
        "truncate idl_private.retired_assets;",
    ]
    for asset in catalog["assets"]:
        lines.append(
            "insert into idl_private.asset_catalog "
            "(asset_id, pack_id, pack_version, category, tier, widget_safe) values ("
            f"'{asset['assetId']}', '{asset['packId']}', {asset['packVersion']}, "
            f"'{asset['category']}', '{asset['tier']}', "
            f"{'true' if asset['widgetSafe'] else 'false'});"
        )
    for old, new in catalog["retired"].items():
        lines.append(
            f"insert into idl_private.retired_assets (old_id, new_id) values ('{old}', '{new}');"
        )
    lines.append("")
    return "\n".join(lines)


def write(catalog: dict) -> None:
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_SQL.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(catalog, indent=2) + "\n", encoding="utf-8")
    OUT_SQL.write_text(sql_seed(catalog), encoding="utf-8")


def check() -> None:
    catalog = build()
    expected_json = json.dumps(catalog, indent=2) + "\n"
    expected_sql = sql_seed(catalog)
    if not OUT_JSON.exists() or OUT_JSON.read_text(encoding="utf-8").replace("\r\n", "\n") != expected_json:
        raise SystemExit(f"{OUT_JSON} is stale; run: python tools/gen_asset_catalog.py")
    if not OUT_SQL.exists() or OUT_SQL.read_text(encoding="utf-8").replace("\r\n", "\n") != expected_sql:
        raise SystemExit(f"{OUT_SQL} is stale; run: python tools/gen_asset_catalog.py")
    print("asset catalog ok")


def main(argv: list[str]) -> int:
    if len(argv) > 1 and argv[1] == "check":
        check()
        return 0
    write(build())
    print(f"wrote {OUT_JSON.relative_to(ROOT)} and {OUT_SQL.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
