-- AP-7: schema 3 avatars on the server, asset catalog, PresenceView v2 (D-41, D-46, F-19).
-- The init migration is not edited. Catalog rows are generated by tools/gen_asset_catalog.py.

create table idl_private.asset_catalog (
  asset_id text primary key,
  pack_id text not null,
  pack_version int not null,
  category text not null,
  tier text not null check (tier in ('free', 'premium')),
  widget_safe boolean not null default true
);

create table idl_private.retired_assets (
  old_id text primary key,
  new_id text not null
);

\ir ../seed/asset_catalog_seed.sql

-- Kotlin AvatarConfiguration encodes defaults (encodeDefaults=true, explicitNulls=false).
-- Every identity the server returns must match that envelope so privacy vectors compare equal.
create or replace function idl_private.identity_envelope(p jsonb) returns jsonb language sql immutable as $$
  select jsonb_strip_nulls(p) || jsonb_build_object(
    'styleDna', coalesce(p -> 'styleDna', jsonb_build_object(
      'styleFamily', 'cozy',
      'expressionIntensity', 'medium',
      'sceneDetailPreference', 'low_detail',
      'motionPreference', 'subtle',
      'semanticVisualOverrides', '{}'::jsonb)),
    'renderVersion', coalesce((p ->> 'renderVersion')::int, 2),
    'schemaVersion', 3,
    'packId', coalesce(nullif(p ->> 'packId', ''), 'core_proto'),
    'packVersion', coalesce((p ->> 'packVersion')::int, 1),
    'familyId', coalesce(nullif(p ->> 'familyId', ''), 'teardrop_face'),
    'itemIds', coalesce(p -> 'itemIds', '{}'::jsonb),
    'colorOverrides', coalesce(p -> 'colorOverrides', '{}'::jsonb),
    'unlinkedSlots', coalesce(p -> 'unlinkedSlots', '[]'::jsonb),
    'itemTransforms', coalesce(p -> 'itemTransforms', '{}'::jsonb),
    'background', coalesce(p -> 'background', '{"mode":"scene"}'::jsonb),
    'signatureFeatureAssetIds', coalesce(p -> 'signatureFeatureAssetIds', '[]'::jsonb),
    'restingExpressionId', coalesce(p ->> 'restingExpressionId', 'neutral')
  )
$$;

create or replace function idl_private.default_avatar() returns jsonb language sql immutable as $$
  select idl_private.identity_envelope(jsonb_build_object(
    'baseAssetId', 'base_teardrop',
    'paletteAssetId', 'palette_sunny',
    'defaultSceneAssetId', 'scene_plain',
    'defaultFrameAssetId', 'frame_squircle',
    'restingExpressionId', 'neutral'))
$$;

-- v1 AvatarConfig (baseForm) or an older schema → schema 3 teardrop. Hair and species marks that
-- do not fit are dropped the same way LegacyAvatarMigration does on the client.
create or replace function idl_private.migrate_avatar_config(p_config jsonb) returns jsonb
language plpgsql immutable as $$
declare
  v_base text;
  v_palette text := 'palette_sunny';
  v_features jsonb := '[]'::jsonb;
  v_head text;
  v_face text;
  v_body text;
  v_prop text;
  v_scene text := 'scene_plain';
  v_frame text := 'frame_squircle';
  v_eyes text;
  v_resting text := 'neutral';
  v_body_color int;
  v_out jsonb;
begin
  if p_config is null or jsonb_typeof(p_config) <> 'object' then
    return idl_private.default_avatar();
  end if;
  if coalesce((p_config ->> 'schemaVersion')::int, 0) > 3 then
    return p_config;
  end if;
  if p_config ? 'baseAssetId' and coalesce((p_config ->> 'schemaVersion')::int, 0) >= 2 then
    v_out := p_config || jsonb_build_object(
      'baseAssetId', 'base_teardrop',
      'schemaVersion', 3,
      'packId', coalesce(nullif(p_config ->> 'packId', ''), 'core_proto'),
      'familyId', coalesce(nullif(p_config ->> 'familyId', ''), 'teardrop_face'));
    if v_out ? 'signatureFeatureAssetIds' then
      v_out := v_out || jsonb_build_object(
        'signatureFeatureAssetIds',
        coalesce((
          select jsonb_agg(value)
          from jsonb_array_elements_text(v_out -> 'signatureFeatureAssetIds') value
          where value in ('feature_blush', 'feature_freckles')
        ), '[]'::jsonb));
    end if;
    return idl_private.identity_envelope(v_out);
  end if;

  -- v1 enums.
  v_base := lower(coalesce(p_config ->> 'baseForm', 'human'));
  v_body_color := coalesce((p_config ->> 'bodyColor')::int, -11172);
  v_palette := case v_body_color
    when -11172 then 'palette_sunny' when -544153 then 'palette_peach' when -2514822 then 'palette_tan'
    when -7513282 then 'palette_cocoa' when -24649 then 'palette_bubblegum' when -6631188 then 'palette_sky'
    when -4661080 then 'palette_mint' when -3952159 then 'palette_lavender' when -724502 then 'palette_moonlight'
    when -5195580 then 'palette_steel' when -24763 then 'palette_ember' when -8399734 then 'palette_lime'
    else 'palette_sunny' end;
  if lower(coalesce(p_config ->> 'faceStyle', 'classic')) = 'blushy' then
    v_features := '["feature_blush"]'::jsonb;
  elsif lower(p_config ->> 'faceStyle') = 'freckles' then
    v_features := '["feature_freckles"]'::jsonb;
  end if;
  v_head := case lower(coalesce(p_config ->> 'headAccessory', 'none'))
    when 'none' then null else 'head_' || lower(p_config ->> 'headAccessory') end;
  v_face := case lower(coalesce(p_config ->> 'faceAccessory', 'none'))
    when 'glasses' then 'face_glasses_round'
    when 'sunglasses' then 'face_sunglasses'
    else null end;
  v_body := case lower(coalesce(p_config ->> 'bodyAccessory', 'none'))
    when 'none' then null else 'body_' || lower(p_config ->> 'bodyAccessory') end;
  v_prop := case lower(coalesce(p_config ->> 'handProp', 'none'))
    when 'none' then null
    when 'pizza' then 'prop_snack'
    else 'prop_' || lower(p_config ->> 'handProp') end;
  v_scene := case lower(coalesce(p_config ->> 'scene', 'plain_gradient'))
    when 'plain_gradient' then 'scene_plain'
    when 'desk_setup' then 'scene_desk'
    when 'dungeon_tavern' then 'scene_tavern'
    when 'space_station' then 'scene_space_station'
    when 'cloudscape' then 'scene_clouds'
    else 'scene_' || lower(p_config ->> 'scene') end;
  if v_base = 'pixel' then
    v_eyes := 'eyefam_pixel';
    v_frame := 'frame_pixel';
  else
    v_frame := case lower(coalesce(p_config ->> 'frameStyle', 'squircle'))
      when 'circle' then 'frame_circle' else 'frame_squircle' end;
  end if;
  v_resting := lower(coalesce(p_config ->> 'expression', 'neutral'));
  return idl_private.identity_envelope(jsonb_strip_nulls(jsonb_build_object(
    'baseAssetId', 'base_teardrop',
    'paletteAssetId', v_palette,
    'eyeFamilyAssetId', v_eyes,
    'signatureFeatureAssetIds', v_features,
    'signatureHeadAccessoryAssetId', v_head,
    'signatureFaceAccessoryAssetId', v_face,
    'signatureBodyAccessoryAssetId', v_body,
    'defaultPropAssetId', v_prop,
    'defaultSceneAssetId', v_scene,
    'defaultFrameAssetId', v_frame,
    'restingExpressionId', v_resting)));
end $$;

create or replace function idl_private.minimal_identity(p_config jsonb) returns jsonb language sql immutable as $$
  select idl_private.identity_envelope(jsonb_build_object(
    'baseAssetId', 'base_teardrop',
    'paletteAssetId', coalesce(p_config ->> 'paletteAssetId', 'palette_sunny'),
    'restingExpressionId', 'neutral'))
$$;

create or replace function idl_private.prop_asset_id(p_prop text) returns text language sql immutable as $$
  select case lower(p_prop)
    when 'none' then null
    when 'pizza' then 'prop_snack'
    else 'prop_' || lower(p_prop) end
$$;

create or replace function idl_private.head_asset_id(p text) returns text language sql immutable as $$
  select case when p is null or lower(p) = 'none' then null else 'head_' || lower(p) end
$$;

create or replace function idl_private.body_asset_id(p text) returns text language sql immutable as $$
  select case when p is null or lower(p) = 'none' then null else 'body_' || lower(p) end
$$;

create or replace function idl_private.scene_asset_id(p text) returns text language sql immutable as $$
  select case lower(p)
    when 'plain_gradient' then 'scene_plain'
    when 'desk_setup' then 'scene_desk'
    when 'dungeon_tavern' then 'scene_tavern'
    when 'space_station' then 'scene_space_station'
    when 'cloudscape' then 'scene_clouds'
    else 'scene_' || lower(p) end
$$;

-- Presence visuals the client may draw. expressionId is set only when mood is visible (F-19).
create or replace function idl_private.presence_visual(p_resolved jsonb, p_mood_visible boolean) returns jsonb
language sql immutable as $$
  select jsonb_strip_nulls(jsonb_build_object(
    'expressionId', case when p_mood_visible then coalesce(
      p_resolved #>> '{visual,expression}',
      idl_private.expression_for(p_resolved ->> 'mood', p_resolved ->> 'availability')) end,
    'propAssetId', idl_private.prop_asset_id(p_resolved #>> '{visual,props,0}'),
    'headAccessoryAssetId', idl_private.head_asset_id(p_resolved #>> '{visual,headAccessory}'),
    'bodyAccessoryAssetId', idl_private.body_asset_id(p_resolved #>> '{visual,bodyAccessory}'),
    'sceneAssetId', case when p_resolved #>> '{visual,scene}' is not null
      then idl_private.scene_asset_id(p_resolved #>> '{visual,scene}') end))
$$;

create or replace function idl_private.presence_view(p_viewer uuid, p_owner uuid, p_at timestamptz) returns jsonb
language plpgsql stable as $$
declare
  v_base jsonb; r jsonb; v_identity jsonb; v_act jsonb; v_view jsonb; v_visual jsonb;
  v_invisible boolean; can_avatar boolean; can_mood boolean; cat_visible boolean; join_visible boolean;
begin
  select config into v_base from public.avatar_configurations where user_id = p_owner;
  v_base := idl_private.migrate_avatar_config(coalesce(v_base, idl_private.default_avatar()));
  r := idl_private.resolve_presence(p_owner, p_at);
  v_act := nullif(r -> 'activity', 'null'::jsonb);

  if p_viewer = p_owner then
    v_visual := idl_private.presence_visual(r, true);
    return jsonb_strip_nulls(jsonb_build_object(
      'userId', p_owner, 'identity', v_base,
      'mood', r -> 'mood', 'availability', r -> 'availability', 'intent', r -> 'intent',
      'activityType', v_act -> 'type', 'activityLabel', v_act -> 'label',
      'joinable', v_act -> 'joinable', 'joinUrl', v_act -> 'joinUrl',
      'note', r -> 'note', 'visual', nullif(v_visual, '{}'::jsonb),
      'updatedAt', r -> 'updatedAt', 'expiresAt', r -> 'expiresAt'));
  end if;

  if not idl_private.are_friends(p_owner, p_viewer) or idl_private.blocked_either(p_owner, p_viewer) then
    return null;
  end if;

  can_avatar := idl_private.can_see(p_owner, p_viewer, 'avatar');
  v_identity := case when can_avatar then v_base else idl_private.minimal_identity(v_base) end;

  select invisible into v_invisible from public.profiles where id = p_owner;
  if coalesce(v_invisible, false) or (r ->> 'isEmpty')::boolean then
    return jsonb_build_object('userId', p_owner, 'identity', v_identity);
  end if;

  can_mood := idl_private.can_see(p_owner, p_viewer, 'mood');
  cat_visible := v_act is not null and idl_private.can_see(p_owner, p_viewer, 'activity_category');
  join_visible := cat_visible and idl_private.can_see(p_owner, p_viewer, 'joinable');
  v_visual := case when can_avatar then idl_private.presence_visual(r, can_mood) end;

  v_view := jsonb_strip_nulls(jsonb_build_object(
    'userId', p_owner, 'identity', v_identity,
    'mood', case when can_mood then r -> 'mood' end,
    'availability', case when idl_private.can_see(p_owner, p_viewer, 'availability') then r -> 'availability' end,
    'intent', case when idl_private.can_see(p_owner, p_viewer, 'intent') then r -> 'intent' end,
    'activityType', case when cat_visible then v_act -> 'type' end,
    'activityLabel', case when cat_visible and idl_private.can_see(p_owner, p_viewer, 'activity_name') then v_act -> 'label' end,
    'joinable', case when join_visible then v_act -> 'joinable' end,
    'joinUrl', case when join_visible then v_act -> 'joinUrl' end,
    'note', case when idl_private.can_see(p_owner, p_viewer, 'status_note') then r -> 'note' end,
    'visual', nullif(v_visual, '{}'::jsonb),
    'updatedAt', case when idl_private.can_see(p_owner, p_viewer, 'last_updated') then r -> 'updatedAt' end));

  if v_view ?| array['mood', 'availability', 'intent', 'activityType', 'note'] or v_view ? 'visual' then
    v_view := v_view || jsonb_build_object('expiresAt', r -> 'expiresAt');
  end if;
  return v_view;
end $$;

create or replace function idl_private.assert_free_asset(p_id text, p_field text) returns void
language plpgsql stable as $$
begin
  if p_id is null then return; end if;
  if exists (select 1 from idl_private.retired_assets where old_id = p_id) then
    perform idl_private.fail('PT400', 'Retired asset', p_field);
  end if;
  if not exists (select 1 from idl_private.asset_catalog where asset_id = p_id) then
    perform idl_private.fail('PT400', 'Unknown asset', p_field);
  end if;
  if exists (select 1 from idl_private.asset_catalog where asset_id = p_id and tier <> 'free') then
    perform idl_private.fail('PT403', 'That item is not unlocked yet', p_field);
  end if;
end $$;

create or replace function public.get_avatar() returns jsonb
language plpgsql security definer set search_path = public, pg_temp as $$
declare v_uid uuid := idl_private.require_uid();
begin
  return idl_private.migrate_avatar_config(
    coalesce((select config from avatar_configurations where user_id = v_uid), idl_private.default_avatar()));
end $$;

create or replace function public.put_avatar(p_config jsonb) returns jsonb
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_uid uuid := idl_private.require_uid();
  v_config jsonb;
  v_id text;
begin
  if jsonb_typeof(p_config) <> 'object'
     or coalesce((p_config ->> 'schemaVersion')::int, 0) <> 3
     or coalesce(p_config ->> 'baseAssetId', '') = ''
     or coalesce(p_config ->> 'paletteAssetId', '') = '' then
    perform idl_private.fail('PT400', 'Invalid avatar', 'config');
  end if;
  perform idl_private.assert_free_asset(p_config ->> 'baseAssetId', 'baseAssetId');
  perform idl_private.assert_free_asset(p_config ->> 'paletteAssetId', 'paletteAssetId');
  perform idl_private.assert_free_asset(p_config ->> 'eyeFamilyAssetId', 'eyeFamilyAssetId');
  perform idl_private.assert_free_asset(p_config ->> 'mouthFamilyAssetId', 'mouthFamilyAssetId');
  perform idl_private.assert_free_asset(p_config ->> 'signatureHeadAccessoryAssetId', 'signatureHeadAccessoryAssetId');
  perform idl_private.assert_free_asset(p_config ->> 'signatureFaceAccessoryAssetId', 'signatureFaceAccessoryAssetId');
  perform idl_private.assert_free_asset(p_config ->> 'signatureBodyAccessoryAssetId', 'signatureBodyAccessoryAssetId');
  perform idl_private.assert_free_asset(p_config ->> 'defaultPropAssetId', 'defaultPropAssetId');
  perform idl_private.assert_free_asset(p_config ->> 'defaultSceneAssetId', 'defaultSceneAssetId');
  perform idl_private.assert_free_asset(p_config ->> 'defaultFrameAssetId', 'defaultFrameAssetId');
  for v_id in select jsonb_array_elements_text(coalesce(p_config -> 'signatureFeatureAssetIds', '[]'::jsonb)) loop
    perform idl_private.assert_free_asset(v_id, 'signatureFeatureAssetIds');
  end loop;
  for v_id in
    select jsonb_array_elements_text(value)
    from jsonb_each(coalesce(p_config -> 'itemIds', '{}'::jsonb))
  loop
    perform idl_private.assert_free_asset(v_id, 'itemIds');
  end loop;

  v_config := idl_private.migrate_avatar_config(p_config);
  insert into avatar_configurations (user_id, config, render_version, updated_at)
  values (v_uid, v_config, coalesce((v_config ->> 'renderVersion')::int, 2), now())
  on conflict (user_id) do update set config = excluded.config, render_version = excluded.render_version, updated_at = now();
  perform idl_private.notify_friends(v_uid, jsonb_build_object('type', 'presence_changed', 'userId', v_uid));
  return v_config;
end $$;

-- Existing rows become schema 3 teardrops in place.
update public.avatar_configurations
set config = idl_private.migrate_avatar_config(config),
    render_version = coalesce((idl_private.migrate_avatar_config(config) ->> 'renderVersion')::int, 2),
    updated_at = now();
